### ISSUE TITLE
preexisting-btrfs failing on rhel10: "org.fedoraproject.Anaconda.Modules.Storage:CRITICAL:program:The function 'bd_btrfs_list_subvolumes' called, but not implemented!"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1105]
```
00:33:38,022 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:blivet:added btrfs volume btrfs.21 (id 21) to device tree
00:33:38,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:blivet:                         BTRFSVolumeDevice.setup: btrfs.21 ; orig: True ; status: True ; controllable: False ;
00:33:38,025 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running... udevadm settle --timeout=300
00:33:38,055 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 0
00:33:38,062 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:testdata:sysfs attr /sys/class/block/sr0/device/model: 51454d55204456442d524f4d202020200a
00:33:38,062 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:testdata:sysfs attr /sys/class/block/sr1/device/model: 51454d55204456442d524f4d202020200a
00:33:38,074 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running... udevadm settle --timeout=300
00:33:38,100 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 0
00:33:38,104 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:testdata:sysfs attr /sys/class/block/sr0/device/model: 51454d55204456442d524f4d202020200a
00:33:38,105 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:testdata:sysfs attr /sys/class/block/sr1/device/model: 51454d55204456442d524f4d202020200a
00:33:38,110 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running... udevadm settle --timeout=300
00:33:38,134 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 0
00:33:38,140 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:testdata:sysfs attr /sys/class/block/sr0/device/model: 51454d55204456442d524f4d202020200a
00:33:38,142 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:testdata:sysfs attr /sys/class/block/sr1/device/model: 51454d55204456442d524f4d202020200a
00:33:38,147 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running... udevadm settle --timeout=300
00:33:38,176 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 0
00:33:38,180 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:testdata:sysfs attr /sys/class/block/sr0/device/model: 51454d55204456442d524f4d202020200a
00:33:38,183 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:testdata:sysfs attr /sys/class/block/sr1/device/model: 51454d55204456442d524f4d202020200a
00:33:38,185 DEBUG anaconda:anaconda: ui.gui: Detected primary monitor: 1280x800 100dpix 100dpiy
00:33:38,189 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running... mount -t btrfs -o subvolid=5 /dev/vda1 /tmp/btrfs-tmp.21m0yybn_l
00:33:38,210 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:stderr:
00:33:38,211 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:b"mount: /tmp/btrfs-tmp.21m0yybn_l: unknown filesystem type 'btrfs'."
00:33:38,214 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:b'       dmesg(1) may have more information after failed mount system call.'
00:33:38,214 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 32
00:33:38,214 WARNING org.fedoraproject.Anaconda.Modules.Storage:CRITICAL:program:The function 'bd_btrfs_list_subvolumes' called, but not implemented!
00:33:38,214 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:blivet:failed to list subvolumes: The function 'bd_btrfs_list_subvolumes' called, but not implemented!
00:33:38,214 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running... umount /tmp/btrfs-tmp.21m0yybn_l
00:33:38,239 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:stderr:
00:33:38,239 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:b'umount: /tmp/btrfs-tmp.21m0yybn_l: not mounted.'
00:33:38,239 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 32
00:33:38,244 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:blivet:                         BTRFSVolumeDevice.setup: btrfs.21 ; orig: True ; status: True ; controllable: False ;
00:33:38,246 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running... udevadm settle --timeout=300
00:33:38,312 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 0
00:33:38,322 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:testdata:sysfs attr /sys/class/block/sr0/device/model: 51454d55204456442d524f4d202020200a
00:33:38,322 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:testdata:sysfs attr /sys/class/block/sr1/device/model: 51454d55204456442d524f4d202020200a
00:33:38,331 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running... mount -t btrfs -o subvolid=5 /dev/vda1 /tmp/btrfs-tmp.21ytjidxmm
00:33:38,344 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:stderr:
00:33:38,344 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:b"mount: /tmp/btrfs-tmp.21ytjidxmm: unknown filesystem type 'btrfs'."
00:33:38,344 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:b'       dmesg(1) may have more information after failed mount system call.'
00:33:38,344 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 32
00:33:38,344 WARNING org.fedoraproject.Anaconda.Modules.Storage:CRITICAL:program:The function 'bd_btrfs_list_subvolumes' called, but not implemented!
00:33:38,344 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:blivet:failed to list subvolumes: The function 'bd_btrfs_list_subvolumes' called, but not implemented!
00:33:38,344 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running... umount /tmp/btrfs-tmp.21ytjidxmm
00:33:38,354 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:stderr:
00:33:38,355 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:b'umount: /tmp/btrfs-tmp.21ytjidxmm: not mounted.'
00:33:38,361 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 32
00:33:38,361 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:blivet:got format: existing btrfs filesystem
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/14741791/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/14741792/virt-install.log)

**Comment by vojtechtrefny** [comment]
So the problem is the CRITICAL log message, the installation actually didn't fail?

**Comment by vojtechtrefny** [comment]
This should be fixed by https://github.com/storaged-project/blivet/pull/1217

**Comment by jstodola** [comment]
The problem still exists in python-blivet-3.10.0-1.el10, reported as https://issues.redhat.com/browse/RHEL-36190.

**Comment by jstodola** [comment]
The problem is fixed in python-blivet-3.10.0-2.el10: https://issues.redhat.com/browse/RHEL-36190
PR to re-enable the test: https://github.com/rhinstaller/kickstart-tests/pull/1183
